controller_frequency: 10
controller_patience: 3

planner_frequency: 1
planner_patience: 20.0

oscillation_timeout: 5.0
oscillation_distance: 0.2

base_local_planner: "local_planner/DWAPlannerROS"
base_global_planner: "global_planner/GlobalPlanner"

shutdown_costmaps: false
