#robot_radius: 0.2
footprint: [[-0.290, -0.290], [-0.290, 0.290], [0.290, 0.290],[0.46, 0.0],  [0.290, -0.290]]
footprint_clearing_enabled: true

laser_layer:
  obstacle_range: 11.5
  raytrace_range: 12.0
  max_obstacle_height: 0.7
  track_unknown_space: false
  observation_sources: rplidar
  rplidar:
    data_type: LaserScan
    topic: scan
    sensor_frame: base_scan
    marking: true
    clearing: true
    inf_is_valid: true

depth_layer:
  obstacle_range: 2.5
  raytrace_range: 9.0
  max_obstacle_height: 0.7
  track_unknown_space: true
  observation_sources: depth
  depth:
    data_type: PointCloud2
    topic: rtabmap/depth/color/obstacles
    marking: true
    clearing: true

inflation_layer:
  cost_scaling_factor: 10.0
  inflation_radius: 1.0
