GlobalPlanner:
#All added by MB
  allow_unknown: false
  use_quadratic: true
  use_dijkstra: true
  use_grid_path: false
  visualize_potential: true
  default_tolerance: 0.3
  cost_factor: 3.0
  neutral_cost: 50
  lethal_cost: 253
