DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.15
  min_vel_x: -0.05

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.15
  min_vel_trans:  0.13

  max_vel_theta: 1.25
  min_vel_theta: 0.9

  acc_lim_x: 1.5
  acc_lim_y: 0.0
  acc_lim_theta: 1.75 

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.25
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 2.0 #Modified - NJ default 2.0 #Edited from 2.0 to 3.0
  sim_granularity: 0.025  #Added by NJ
  vx_samples: 20 #20 0.2 - NJ updated.
  vy_samples: 0 #Edited from 10 to 0 (no vel y samples)
  vth_samples: 20  #40 - modified NJ
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 32.0 # 32.0 - NJ modified
  goal_distance_bias: 24.0 #Updated - NJ default: 20 
  occdist_scale: 15 #Updated - NJ default: 0.02 #Edited from 20 to 15
  forward_point_distance: 0.325
  stop_time_buffer: 1 # 0.2 - NJ modified
  scaling_speed: 0.1 # 0.25 - NJ updated.
  max_scaling_factor: 0.5 # 0.2 - NJ updated. #Edited from 1 to 0.5

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
